name: job_seeker
description: A Flutter project to manage job offers.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.1
  flutter_html: ^2.0.0
  html_unescape: ^2.0.0 # Biblioteka do dekodowania HTML
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/job_logo.png  # Ścieżka do pliku obrazu
  uses-material-design: true
